. ~/.bashrc
. ~/projects/powerlevel9k/powerlevel9k.zsh-theme

SHELL=/bin/zsh

vaulted_status() {
  if [[ -z "${VAULTED_ENV}" ]]; then
    echo -n ""
  else
    exp=$(date -j -f "%Y-%m-%dT%H:%M:%S%z" "${VAULTED_ENV_EXPIRATION/Z/+0000}" +%s)
    now=$(date +%s)
    rem=$(date -j -f "%s" "$(($exp - $now))" +%H:%M:%S)
    echo -n "${VAULTED_ENV} (${rem})"
  fi
}

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs custom_vaulted_status)
POWERLEVEL9K_DIR_BACKGROUND='015'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_USER_DEFAULT_BACKGROUND='235'
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='009'

POWERLEVEL9K_CUSTOM_VAULTED_STATUS="vaulted_status"
POWERLEVEL9K_CUSTOM_VAULTED_STATUS_BACKGROUND='231'

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(battery time)
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

POWERLEVEL9K_BATTERY_CHARGING='yellow'
POWERLEVEL9K_BATTERY_CHARGED='green'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='46'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='235'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='178'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='235'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='88'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='235'
POWERLEVEL9K_BATTERY_CHARGED_ICON='/UF240'
POWERLEVEL9K_BATTERY_LOW_ICON='/UF240'
POWERLEVEL9K_BATTERY_CHARGING_ICON='/UF1E6'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='235'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='014'
POWERLEVEL9K_BATTERY_ICON='\UF1E6'
POWERLEVEL9K_BATTERY_VERBOSE=false
